const SHOW_MODAL = 'SHOW_MODAL';
const CLOSE_MODAL = 'SHOW_MODAL';
const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL';
const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
const ADD_PRODUCT = 'ADD_PRODUCT';
const ADD_COUNT = 'ADD_COUNT';
const UPDATE_ORDER = 'UPDATE_PRODUCT';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const SIGN_IN = 'SIGN_IN';
const ON_SIGNIN = 'ON_SIGNIN';
export default {
    SHOW_MODAL,
    CLOSE_MODAL,
    SHOW_SIGNIN_MODAL,
    SHOW_SIGNUP_MODAL,
    ADD_COUNT,
    ADD_PRODUCT,
    UPDATE_ORDER,
    INCREMENT,
    DECREMENT,
    SIGN_IN,
    ON_SIGNIN,
};
