const SHOW_MODAL = 'SHOW_MODAL';
const CLOSE_MODAL = 'SHOW_MODAL';
const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL';
const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
const ADD_PRODUCT = 'ADD_PRODUCT';
const ADD_COUNT = 'ADD_COUNT';
const UPDATE_ORDER = 'UPDATE_PRODUCT';
const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const SIGN_IN = 'SIGN_IN';
const ON_SIGNIN = 'ON_SIGNIN';
const ADD_ID = 'ADD_ID';
const ADD_KEY = 'ADD_KEY';
const DELETE_ORDER = 'DELETE_ORDER';
const SUB_COUNT = 'SUB_COUNT';
const SIGN_UP = 'SIGN_UP';
const ON_SIGN_UP = 'ON_SIGN_UP';
const ALL_CATEGORY = 'ALL_CATEGORY';
const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY';
const PRODUCT = 'PRODUCT';
const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT';
export default {
    SHOW_MODAL,
    CLOSE_MODAL,
    SHOW_SIGNIN_MODAL,
    SHOW_SIGNUP_MODAL,
    ADD_COUNT,
    ADD_PRODUCT,
    UPDATE_ORDER,
    INCREMENT,
    DECREMENT,
    SIGN_IN,
    ON_SIGNIN,
    ADD_ID,
    ADD_KEY,
    DELETE_ORDER,
    SUB_COUNT,
    SIGN_UP,
    ON_SIGN_UP,
    ALL_CATEGORY,
    GET_ALL_CATEGORY,
    PRODUCT,
    GET_ALL_PRODUCT,
};
